### ISSUE TITLE
Add more Algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Ruby#1]
Please add more algorithms to this repo. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by RaiVaibhav** [comment]
@AnupKumarPanwar  Sir help me in clearing my one doubt that they said they u have to make a pull request in between 1-31 october but we can see that its 28th of september and everyone started PR to any issue , i really don't know whether my contribution will get counted or not??

**Comment by dynamitechetan** [comment]
Contribute if you want. IF you only want it for hacktoberfest then please send a PR after 1 Oct.

**Comment by RaiVaibhav** [comment]
I was new so i get excited ,hope you understand my point

**Comment by dynamitechetan** [comment]
Cool 🎉

**Comment by dippersauce** [comment]
I have a few ready to submit after Hacktoberfest starts. They mostly are relevant to PRNG, such as MT199937 and ARC4. Would you be interested in those algorithms?

**Comment by dynamitechetan** [comment]
yeah cool.

**Comment by simonszu** [comment]
I started with implementing some data structures, but have just completed a single linked list. I think i will create a pull request every time when i have completed a whole topic, e.g. a complete folder like on TheAlgorithms/Python repo.

**Comment by JuantAldea** [comment]
Are the PRs going to be merged?

**Comment by vbrazo** [comment]
As a follow-up to this issue, I created a new issue with a list of algorithms that the Python directory currently has and I'm closing this issue for now since it's stale. Thanks.
