### ISSUE TITLE
Add RuboCop?

### ISSUE THREAD

**Issue by vzvu3k6k** [TheAlgorithms/Ruby#113]
# Problems to solve

This project doesn't have a coding style guideline or linters. This causes two problems:

 * It is too cumbersome to manually find simple coding style issues (for both contributors and reviewers).
 * Different tastes in coding styles between contributors can lead to inconsistencies and confuse new contributors.

# Possible solutions

* Add RuboCop to this project (and check code in CI?)

# Possible risks

* The default RuboCop rules might be too strict or controversial?
    * Starting from the minimum rules will be better.
    * Link: https://www.rubypigeon.com/posts/my-beef-with-rubocop/

# Links

 - Originally proposed by @vbrazo at https://github.com/TheAlgorithms/Ruby/pull/112#pullrequestreview-622760103

**Comment by vzvu3k6k** [comment]
@vbrazo I've created an issue for now. Please feel free to rewrite the description.

**Comment by msaf9** [comment]
@vbrazo I have implemented RuboCop in my local Ruby repository. I found some issues. Here is the report of the RuboCop: **90 files inspected, 498 offenses detected, 255 offenses auto-correctable**. 
Shall I go ahead and implement this for the remote repository or tweak it to make it a little simple?
[report.txt](https://github.com/TheAlgorithms/Ruby/files/6331117/report.txt)

**Comment by vbrazo** [comment]
@msaf9 what `.rubocop.yml` are we proposing? Could you please post here so we could take a look?
