### ISSUE TITLE
Let's Unify the naming convention with snake case( folder )

### ISSUE THREAD

**Issue by Doppon** [TheAlgorithms/Ruby#61]
I think in ruby, it use snake case for file name and folder name too.

ref: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/FileName

**Comment by Doppon** [comment]
I created the pull request.

https://github.com/TheAlgorithms/Ruby/pull/62

**Comment by vzvu3k6k** [comment]
Solved by #62 :tada:
